#!/bin/bash
#PBS -N gstacks_reducta4
#PBS -l select=1:ncpus=8:mem=32gb
#PBS -l walltime=12:00:00
#PBS -j oe
#PBS -o /storage/plzen1/home/m_stjepanovic/reducta_clean/reducta_4pop/09_logs/gstacks_reducta_4pop.pbs.log

set -euo pipefail

module load stacks

BASE=/storage/plzen1/home/m_stjepanovic/reducta_clean/reducta_4pop
BAMDIR=$BASE/01_bams
POPMAP=$BASE/02_metadata/popmap_reducta_new.txt
OUT=$BASE/03_gstacks

mkdir -p "$OUT"

echo "Running gstacks for Reducta-only 4-population dataset"
date

gstacks \
  -I "$BAMDIR" \
  -M "$POPMAP" \
  -O "$OUT" \
  -t 8

echo "gstacks finished"
date
